"""add_ui_modules

Revision ID: 011
Revises: 010
Create Date: 2026-02-18 14:45:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "011"
down_revision: Union[str, None] = "010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    
    # Create ui_modules table
    op.create_table(
        "ui_modules",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "cuenta_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("accounts.id", ondelete="CASCADE"),
            nullable=True,
            index=True,
        ),
        sa.Column("codigo", sa.String(50), nullable=False),
        sa.Column("nombre", sa.String(100), nullable=False),
        sa.Column("descripcion", sa.String(500), nullable=True),
        sa.Column("ruta", sa.String(200), nullable=False),
        sa.Column("icono", sa.String(50), nullable=True),
        sa.Column("orden", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("es_submodulo", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("parent_code", sa.String(50), nullable=True),
        sa.Column("acciones", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("es_sistema", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    
    # Create indexes for ui_modules
    op.create_index("ix_ui_modules_codigo", "ui_modules", ["codigo"])
    op.create_index("ix_ui_modules_cuenta_id", "ui_modules", ["cuenta_id"])
    
    # Create role_module_permissions table
    op.create_table(
        "role_module_permissions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "role_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("roles.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "module_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("ui_modules.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "acciones_permitidas",
            postgresql.JSONB(),
            nullable=False,
            server_default="[]",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "module_id", name="uq_role_module"),
    )
    
    # Create indexes for role_module_permissions
    op.create_index(
        "ix_role_module_permissions_role_id", "role_module_permissions", ["role_id"]
    )
    op.create_index(
        "ix_role_module_permissions_module_id", "role_module_permissions", ["module_id"]
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    # Drop role_module_permissions table
    op.drop_index("ix_role_module_permissions_module_id", table_name="role_module_permissions")
    op.drop_index("ix_role_module_permissions_role_id", table_name="role_module_permissions")
    op.drop_table("role_module_permissions")
    
    # Drop ui_modules table
    op.drop_index("ix_ui_modules_cuenta_id", table_name="ui_modules")
    op.drop_index("ix_ui_modules_codigo", table_name="ui_modules")
    op.drop_table("ui_modules")
    
    # ### end Alembic commands ###
