"""add_tipificaciones

Revision ID: 012
Revises: 011
Create Date: 2026-02-18 16:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "012"
down_revision: Union[str, None] = "011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    
    # Create tipificaciones table
    op.create_table(
        "tipificaciones",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "cuenta_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("accounts.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column("nombre", sa.String(100), nullable=False),
        sa.Column("descripcion", sa.String(500), nullable=True),
        sa.Column("color", sa.String(7), nullable=True, server_default="#6B7280"),
        sa.Column("orden", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("activo", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("es_final", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    
    # Create indexes for tipificaciones
    op.create_index("ix_tipificaciones_cuenta_id", "tipificaciones", ["cuenta_id"])
    op.create_index("ix_tipificaciones_activo", "tipificaciones", ["activo"])
    
    # Create subtipificaciones table
    op.create_table(
        "subtipificaciones",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "tipificacion_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tipificaciones.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "cuenta_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("accounts.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column("nombre", sa.String(100), nullable=False),
        sa.Column("descripcion", sa.String(500), nullable=True),
        sa.Column("color", sa.String(7), nullable=True),
        sa.Column("orden", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("activo", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    
    # Create indexes for subtipificaciones
    op.create_index("ix_subtipificaciones_tipificacion_id", "subtipificaciones", ["tipificacion_id"])
    op.create_index("ix_subtipificaciones_cuenta_id", "subtipificaciones", ["cuenta_id"])
    op.create_index("ix_subtipificaciones_activo", "subtipificaciones", ["activo"])
    
    # Add tipificacion columns to leads table
    op.add_column(
        "leads",
        sa.Column(
            "tipificacion_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("tipificaciones.id", ondelete="SET NULL"),
            nullable=True,
            index=True,
        ),
    )
    op.add_column(
        "leads",
        sa.Column(
            "subtipificacion_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("subtipificaciones.id", ondelete="SET NULL"),
            nullable=True,
            index=True,
        ),
    )
    
    # Create indexes for leads tipificacion columns
    op.create_index("ix_leads_tipificacion_id", "leads", ["tipificacion_id"])
    op.create_index("ix_leads_subtipificacion_id", "leads", ["subtipificacion_id"])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    # Drop indexes from leads
    op.drop_index("ix_leads_subtipificacion_id", table_name="leads")
    op.drop_index("ix_leads_tipificacion_id", table_name="leads")
    
    # Drop columns from leads
    op.drop_column("leads", "subtipificacion_id")
    op.drop_column("leads", "tipificacion_id")
    
    # Drop subtipificaciones table
    op.drop_index("ix_subtipificaciones_activo", table_name="subtipificaciones")
    op.drop_index("ix_subtipificaciones_cuenta_id", table_name="subtipificaciones")
    op.drop_index("ix_subtipificaciones_tipificacion_id", table_name="subtipificaciones")
    op.drop_table("subtipificaciones")
    
    # Drop tipificaciones table
    op.drop_index("ix_tipificaciones_activo", table_name="tipificaciones")
    op.drop_index("ix_tipificaciones_cuenta_id", table_name="tipificaciones")
    op.drop_table("tipificaciones")
    
    # ### end Alembic commands ###
